# Day 6: Inverse Matrices and Solving Linear Systems

Welcome to Day 6! Today, we delve into one of the most powerful concepts in linear algebra: the inverse of a matrix. Understanding matrix inverses is crucial for solving systems of linear equations, which forms the backbone of many machine learning algorithms.

## Objectives for Today:
- Understand the concept of an **inverse matrix**.
- Implement **matrix inversion** using NumPy.
- Identify **singular matrices** (matrices without an inverse).
- Understand how inverse matrices are used to **solve linear systems** (Ax = b).
- Implement solving linear systems directly using NumPy's `np.linalg.solve()` function.
- Connect these concepts to their applications in Machine Learning.

In [1]:
# Import necessary libraries
import numpy as np

## 1. Inverse Matrices

### Concept
For a square matrix $A$, its inverse, denoted $A^{-1}$, is a matrix such that when multiplied by $A$, it yields the identity matrix $I$. Mathematically, this is expressed as:

$A A^{-1} = A^{-1} A = I$

The identity matrix $I$ is a square matrix with ones on the main diagonal and zeros elsewhere (e.g., for a 2x2 matrix, $I = \begin{pmatrix} 1 & 0 \\ 0 & 1 \end{pmatrix}$). Multiplying any matrix by the identity matrix leaves the original matrix unchanged.

**Key Points:**
-   Only **square matrices** (n x n) can have an inverse.
-   Not all square matrices have inverses. A matrix that does not have an inverse is called a **singular matrix**. A matrix is singular if its determinant is zero.

### NumPy Practice
NumPy's `np.linalg.inv()` function is used to calculate the inverse of a matrix.

In [2]:
# Example 1: Inverting a 2x2 matrix
A = np.array([[2, 1],
              [1, 1]])

print("Original Matrix A:\n", A)

# Calculate the inverse
A_inv = np.linalg.inv(A)
print("\nInverse of A (A_inv):\n", A_inv)

# Verify the inverse: A @ A_inv should be the identity matrix
identity_check = A @ A_inv
print("\nA @ A_inv:\n", identity_check)

# Due to floating-point precision, directly comparing with '==' might fail.
# Use np.allclose() for robust comparison.
is_identity = np.allclose(identity_check, np.eye(2))
print("Is A @ A_inv approximately the identity matrix?", is_identity)

# Example 2: Attempting to invert a singular matrix
S = np.array([[1, 2],
              [2, 4]]) # Determinant is (1*4 - 2*2) = 0

print("\nSingular Matrix S:\n", S)

try:
    S_inv = np.linalg.inv(S)
    print("Inverse of S:\n", S_inv)
except np.linalg.LinAlgError as e:
    print("Error: Cannot invert singular matrix. ", e)


Original Matrix A:
 [[2 1]
 [1 1]]

Inverse of A (A_inv):
 [[ 1. -1.]
 [-1.  2.]]

A @ A_inv:
 [[1. 0.]
 [0. 1.]]
Is A @ A_inv approximately the identity matrix? True

Singular Matrix S:
 [[1 2]
 [2 4]]
Error: Cannot invert singular matrix.  Singular matrix


### **Exercise 1: Matrix Inversion**

1.  Define a 3x3 matrix:
    `M = np.array([[1, 2, 0], [0, 1, 0], [1, 0, 1]])`
2.  Calculate its inverse `M_inv`.
3.  Verify the inversion by multiplying `M` by `M_inv` and checking if the result is approximately the identity matrix.
4.  Define a singular 2x2 matrix:
    `S_singular = np.array([[6, 3], [4, 2]])`
5.  Attempt to calculate the inverse of `S_singular` and print the error message if an error occurs.

In [3]:
# Your code for Exercise 1 here


In [4]:
# Solution for Exercise 1
M = np.array([[1, 2, 0],
              [0, 1, 0],
              [1, 0, 1]])

print("Original Matrix M:\n", M)

# Calculate the inverse
M_inv = np.linalg.inv(M)
print("\nInverse of M (M_inv):\n", M_inv)

# Verify the inverse
identity_check_M = M @ M_inv
print("\nM @ M_inv:\n", identity_check_M)

is_identity_M = np.allclose(identity_check_M, np.eye(3))
print("Is M @ M_inv approximately the identity matrix?", is_identity_M)

# Singular matrix example
S_singular = np.array([[6, 3],
                       [4, 2]])

print("\nSingular Matrix S_singular:\n", S_singular)
try:
    S_singular_inv = np.linalg.inv(S_singular)
    print("Inverse of S_singular:\n", S_singular_inv)
except np.linalg.LinAlgError as e:
    print("Error: Cannot invert singular matrix. ", e)


Original Matrix M:
 [[1 2 0]
 [0 1 0]
 [1 0 1]]

Inverse of M (M_inv):
 [[ 1. -2.  0.]
 [-0.  1. -0.]
 [-1.  2.  1.]]

M @ M_inv:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Is M @ M_inv approximately the identity matrix? True

Singular Matrix S_singular:
 [[6 3]
 [4 2]]
Error: Cannot invert singular matrix.  Singular matrix


## 2. Solving Linear Systems (Ax = b) using Inverse

### Concept
A system of linear equations can be represented in matrix form as:

$A\mathbf{x} = \mathbf{b}$

where:
-   $A$ is the coefficient matrix.
-   $\mathbf{x}$ is the vector of unknown variables.
-   $\mathbf{b}$ is the constant vector.

If $A$ is an invertible square matrix, we can solve for $\mathbf{x}$ by multiplying both sides by $A^{-1}$:

$A^{-1} A\mathbf{x} = A^{-1} \mathbf{b}$
$I\mathbf{x} = A^{-1} \mathbf{b}$
$\mathbf{x} = A^{-1} \mathbf{b}$

This method provides an exact solution to the system. However, computing the inverse of a matrix can be computationally expensive and numerically unstable for large or ill-conditioned matrices. For practical applications, especially in machine learning, direct solvers are often preferred (as we'll see in the next section).

### NumPy Practice
Let's solve a simple 2x2 system:

$2x + y = 5$
$x + y = 3$

This system can be written as $A\mathbf{x} = \mathbf{b}$ where:

$A = \begin{pmatrix} 2 & 1 \\ 1 & 1 \end{pmatrix}$, $\mathbf{x} = \begin{pmatrix} x \\ y \end{pmatrix}$, $\mathbf{b} = \begin{pmatrix} 5 \\ 3 \end{pmatrix}$

In [5]:
# Define the coefficient matrix A and the constant vector b
A = np.array([[2, 1],
              [1, 1]])
b = np.array([5, 3])

print("Coefficient Matrix A:\n", A)
print("Constant Vector b:", b)

# Calculate the inverse of A
A_inv = np.linalg.inv(A)
print("\nInverse of A (A_inv):\n", A_inv)

# Solve for x using x = A_inv @ b
x = A_inv @ b
print("\nSolution vector x (x, y):", x)

# Verify the solution: A @ x should be equal to b
verification = A @ x
print("\nVerification (A @ x):", verification)
is_correct = np.allclose(verification, b)
print("Is A @ x approximately equal to b?", is_correct)


Coefficient Matrix A:
 [[2 1]
 [1 1]]
Constant Vector b: [5 3]

Inverse of A (A_inv):
 [[ 1. -1.]
 [-1.  2.]]

Solution vector x (x, y): [2. 1.]

Verification (A @ x): [5. 3.]
Is A @ x approximately equal to b? True


### **Exercise 2: Solving a 3x3 System**

Solve the following system of linear equations using matrix inversion:

$x + 2y + z = 4$
$2x + 0y + z = 5$
$x - y + 3z = 3$

1.  Represent the system as $A\mathbf{x} = \mathbf{b}$.
2.  Calculate $A^{-1}$.
3.  Solve for $\mathbf{x}$.
4.  Print matrix $A$, vector $\mathbf{b}$, and the solution vector $\mathbf{x}$.
5.  Verify your solution.

In [6]:
# Your code for Exercise 2 here


In [7]:
# Solution for Exercise 2
A_ex2 = np.array([[1, 2, 1],
                  [2, 0, 1],
                  [1, -1, 3]])

b_ex2 = np.array([4, 5, 3])

print("Coefficient Matrix A:\n", A_ex2)
print("Constant Vector b:", b_ex2)

try:
    A_ex2_inv = np.linalg.inv(A_ex2)
    print("\nInverse of A (A_ex2_inv):\n", A_ex2_inv)

    x_ex2 = A_ex2_inv @ b_ex2
    print("\nSolution vector x (x, y, z):", x_ex2)

    # Verify the solution
    verification_ex2 = A_ex2 @ x_ex2
    print("\nVerification (A @ x):", verification_ex2)
    is_correct_ex2 = np.allclose(verification_ex2, b_ex2)
    print("Is A @ x approximately equal to b?", is_correct_ex2)

except np.linalg.LinAlgError as e:
    print("Error: Matrix A is singular and cannot be inverted. ", e)


Coefficient Matrix A:
 [[ 1  2  1]
 [ 2  0  1]
 [ 1 -1  3]]
Constant Vector b: [4 5 3]

Inverse of A (A_ex2_inv):
 [[-0.09090909  0.63636364 -0.18181818]
 [ 0.45454545 -0.18181818 -0.09090909]
 [ 0.18181818 -0.27272727  0.36363636]]

Solution vector x (x, y, z): [2.27272727 0.63636364 0.45454545]

Verification (A @ x): [4. 5. 3.]
Is A @ x approximately equal to b? True


## 3. Solving Linear Systems Directly with `np.linalg.solve`

### Concept
While using the inverse matrix (`A_inv @ b`) is conceptually clear, it's generally not the recommended approach for solving linear systems in practice, especially with computers.

NumPy's `np.linalg.solve(A, b)` function is a more efficient and numerically stable way to solve $A\mathbf{x} = \mathbf{b}$. This function does not explicitly calculate the inverse of $A$. Instead, it uses a variety of advanced algorithms (like LU decomposition) to find the solution $\mathbf{x}$ directly, which reduces computational errors and improves performance.

It implicitly handles the inverse operation more robustly behind the scenes.

### NumPy Practice
Let's re-solve the previous 2x2 system using `np.linalg.solve`:

$2x + y = 5$
$x + y = 3$

In [8]:
# Define the coefficient matrix A and the constant vector b
A = np.array([[2, 1],
              [1, 1]])
b = np.array([5, 3])

print("Coefficient Matrix A:\n", A)
print("Constant Vector b:", b)

# Solve for x directly using np.linalg.solve
x_direct = np.linalg.solve(A, b)
print("\nSolution vector x (x, y) using np.linalg.solve:", x_direct)

# Verify the solution
verification_direct = A @ x_direct
print("\nVerification (A @ x_direct):", verification_direct)
is_correct_direct = np.allclose(verification_direct, b)
print("Is A @ x_direct approximately equal to b?", is_correct_direct)

# Comparison with the inverse method's result (from previous section)
A_inv = np.linalg.inv(A)
x_inverse = A_inv @ b
print("\nSolution from inverse method:", x_inverse)
print("Are both solutions approximately equal?", np.allclose(x_direct, x_inverse))


Coefficient Matrix A:
 [[2 1]
 [1 1]]
Constant Vector b: [5 3]

Solution vector x (x, y) using np.linalg.solve: [2. 1.]

Verification (A @ x_direct): [5. 3.]
Is A @ x_direct approximately equal to b? True

Solution from inverse method: [2. 1.]
Are both solutions approximately equal? True


### **Exercise 3: Practical Linear System Solution (Linear Regression)**

A common application of solving linear systems in machine learning is in Ordinary Least Squares (OLS) linear regression. For a simple linear model with an intercept, the normal equation to find the optimal coefficients $\beta$ (beta) is:

$(\mathbf{X}^T \mathbf{X}) \mathbf{\beta} = \mathbf{X}^T \mathbf{y}$

where:
-   $\mathbf{X}$ is the design matrix (features, including a column of ones for the intercept).
-   $\mathbf{y}$ is the target vector.

We can rewrite this as $A_{LR} \mathbf{\beta} = \mathbf{b}_{LR}$, where $A_{LR} = \mathbf{X}^T \mathbf{X}$ and $\mathbf{b}_{LR} = \mathbf{X}^T \mathbf{y}$.

Given the following synthetic data:
-   `X = np.array([[1, 2], [1, 3], [1, 4], [1, 5]])` (first column is for the intercept, second is the feature x)
-   `y = np.array([3, 5, 7, 9])` (target values)

1.  Calculate `A_lr = X.T @ X`.
2.  Calculate `b_lr = X.T @ y`.
3.  Solve for the coefficient vector `beta` using `np.linalg.solve(A_lr, b_lr)`.
4.  Print the calculated coefficients (`beta`). The first element is the intercept, and the second is the slope.

In [9]:
# Your code for Exercise 3 here


In [10]:
# Solution for Exercise 3
X = np.array([[1, 2],
              [1, 3],
              [1, 4],
              [1, 5]])
y = np.array([3, 5, 7, 9])

print("Design Matrix X:\n", X)
print("Target Vector y:\n", y)

# Calculate A_lr = X.T @ X
A_lr = X.T @ X
print("\nA_lr (X_transpose @ X):\n", A_lr)

# Calculate b_lr = X.T @ y
b_lr = X.T @ y
print("\nb_lr (X_transpose @ y):\n", b_lr)

# Solve for beta
beta = np.linalg.solve(A_lr, b_lr)
print("\nCoefficients (intercept, slope):", beta)

# You can interpret these coefficients: intercept ~ -1, slope ~ 2
# This means the fitted line is approximately y = 2x - 1

Design Matrix X:
 [[1 2]
 [1 3]
 [1 4]
 [1 5]]
Target Vector y:
 [3 5 7 9]

A_lr (X_transpose @ X):
 [[ 4 14]
 [14 54]]

b_lr (X_transpose @ y):
 [24 94]

Coefficients (intercept, slope): [-1.  2.]


## Day 6 Summary and ML Connection

Today, we explored the critical concepts of inverse matrices and their application in solving linear systems. Here's a recap of what we covered and its relevance to machine learning:

-   **Inverse Matrix ($A^{-1}$):** A matrix that, when multiplied by the original matrix $A$, yields the identity matrix. It's like the reciprocal for numbers, allowing us to 'undo' a matrix transformation.
-   **Singular Matrices:** Matrices that do not have an inverse (their determinant is zero). These matrices represent transformations that cannot be undone, often implying a loss of information or redundancy.
-   **Solving Linear Systems ($A\mathbf{x} = \mathbf{b}$):** We learned how to find the unknown vector $\mathbf{x}$ using two methods:
    1.  **Using the inverse:** $\mathbf{x} = A^{-1} \mathbf{b}$. While conceptually clear, it's often less efficient and numerically stable for computational purposes.
    2.  **Directly with `np.linalg.solve()`:** This is the preferred method in practice, as it uses optimized algorithms for accuracy and speed without explicitly computing the inverse.

**ML Connections:**
-   **Ordinary Least Squares (OLS) Linear Regression:** Solving the normal equation $(\mathbf{X}^T \mathbf{X}) \mathbf{\beta} = \mathbf{X}^T \mathbf{y}$ for the optimal coefficients $\mathbf{\beta}$ is a direct application of solving linear systems. This is fundamental for understanding how linear models find their best fit.
-   **Optimization Problems:** Many iterative optimization algorithms in machine learning (e.g., Newton's method) involve solving systems of linear equations at each step.
-   **Data Transformations:** Understanding matrix inverses helps in comprehending how certain linear transformations (like scaling or rotation) can be reversed if the transformation matrix is invertible. Non-invertible transformations imply that information might be irretrievably lost.

The ability to solve linear systems effectively is a cornerstone of numerical computation in machine learning. As you progress, you'll encounter these operations frequently, making today's practice invaluable!