# Day 3: Matrices and Basic Matrix Operations

Welcome to Day 3! Today, we're moving from single vectors to collections of vectors arranged in rectangular grids called **matrices**. Matrices are central to linear algebra and are used extensively in machine learning to represent datasets, transformations, and model parameters.

## Objectives for Today:

- Understand what matrices are (dimensions, elements, rows, columns).
- Learn how to represent matrices using 2D NumPy arrays.
- Practice accessing individual elements, rows, and columns of a matrix.
- Understand and implement **matrix addition**.
- Understand and implement **scalar multiplication of matrices**.
- Learn how to perform a **matrix transpose**.
- Connect these concepts to data representation and manipulation in Machine Learning.


In [2]:
# Import necessary libraries
import numpy as np

## 1. What are Matrices?

### Concept

A **matrix** is a rectangular array of numbers, symbols, or expressions, arranged in rows and columns. Think of it as a table of numbers.

- A matrix is defined by its **dimensions**, usually written as `m x n` (read as 'm by n'), where `m` is the number of **rows** and `n` is the number of **columns**.
- Each individual number in the matrix is called an **element**.

Example of a 2x3 matrix:

$$
A = \begin{pmatrix}
a_{11} & a_{12} & a_{13} \\
a_{21} & a_{22} & a_{23}
\end{pmatrix}
$$


### NumPy Practice: Creating Matrices

In NumPy, matrices are represented by 2-dimensional arrays. You can create them by passing a list of lists to `np.array()`.


In [4]:
# Creating a 2x3 matrix
matrix_A = np.array([[1, 2, 3], [4, 5, 6]])
print("Matrix A:\n", matrix_A)
print("Shape of Matrix A:", matrix_A.shape)  # Output will be (2, 3)

print("\n---")

# Creating a 3x3 (square) matrix
matrix_B = np.array([[7, 8, 9], [10, 11, 12], [13, 14, 15]])

print("Matrix B:\n", matrix_B)
print("Shape of Matrix B:", matrix_B.shape)  # Output will be (3, 3)

print("\n---")

# Creating a 4x1 (column) vector - technically a matrix with 1 column
column_vector = np.array([[10], [20], [30], [40]])
print("Column Vector (Matrix):\n", column_vector)
print("Shape of Column Vector:", column_vector.shape)  # Output will be (4, 1)

Matrix A:
 [[1 2 3]
 [4 5 6]]
Shape of Matrix A: (2, 3)

---
Matrix B:
 [[ 7  8  9]
 [10 11 12]
 [13 14 15]]
Shape of Matrix B: (3, 3)

---
Column Vector (Matrix):
 [[10]
 [20]
 [30]
 [40]]
Shape of Column Vector: (4, 1)


### **Exercise 1: Creating and Inspecting Matrices**

1.  Create a matrix `M1` with 3 rows and 2 columns, containing any integers you like.
2.  Create a square matrix `M2` of size 4x4, containing floating-point numbers.
3.  Print both matrices and their `shape` attribute.


In [ ]:
# Your code for Exercise 1 here
M1 = np.array([[9, 8], [4, 5], [3, 0]])

M2 = np.array(
    [
        [4.1, 4.2, 4.3, 4.3],
        [4.4, 4.5, 4.6, 4.7],
        [4.8, 4.9, 5.0, 5.1],
        [5.2, 5.3, 5.4, 5.5],
    ]
)

print("M1: \n", M1)
print("\nShape of M1: ", M1.shape)
print("_" * 21)
print("\nM2: \n", M2)
print("\nShape of M2: ", M2.shape)

M1: 
 [[9 8]
 [4 5]
 [3 0]]

Shape of M1:  (3, 2)
_____________________

M2: 
 [[4.1 4.2 4.3 4.3]
 [4.4 4.5 4.6 4.7]
 [4.8 4.9 5.  5.1]
 [5.2 5.3 5.4 5.5]]

Shape of M2:  (4, 4)


In [ ]:
# Solution for Exercise 1
M1 = np.array([[1, 5], [2, 6], [3, 7]])
print("Matrix M1:\n", M1)
print("Shape of M1:", M1.shape)

print("\n---")

M2 = np.array(
    [
        [1.1, 2.2, 3.3, 4.4],
        [5.5, 6.6, 7.7, 8.8],
        [9.9, 10.1, 11.2, 12.3],
        [13.4, 14.5, 15.6, 16.7],
    ]
)
print("Matrix M2:\n", M2)
print("Shape of M2:", M2.shape)

## 2. Accessing Matrix Elements, Rows, and Columns

### Concept

Accessing parts of a matrix is similar to accessing elements in lists or 1D arrays, but now you have two dimensions (row and column index).

- `matrix[row_index, column_index]` for a single element.
- `matrix[row_index, :]` for an entire row.
- `matrix[:, column_index]` for an entire column.
- Slicing works too: `matrix[row_start:row_end, col_start:col_end]`.

### NumPy Practice


In [22]:
data_matrix = np.array([[10, 20, 30, 40], [50, 60, 70, 80], [90, 100, 110, 120]])
print("Original Data Matrix (3x4):\n", data_matrix)

# Accessing a single element (row 0, column 1 - which is 20)
element = data_matrix[2, 2]
print("\nElement at (0, 1):", element)

# Accessing the second row (index 1)
row_1 = data_matrix[1, :]
print("Second Row (index 1):", row_1)

# Accessing the third column (index 2)
col_2 = data_matrix[:, -2]
print("Third Column (index 2):", col_2)

# Accessing a sub-matrix (rows 0-1, columns 0-1)
sub_matrix = data_matrix[0:2, 0:2]  # Rows 0 and 1, Columns 0 and 1
print("Sub-matrix (top-left 2x2):\n", sub_matrix)

Original Data Matrix (3x4):
 [[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]

Element at (0, 1): 110
Second Row (index 1): [50 60 70 80]
Third Column (index 2): [ 30  70 110]
Sub-matrix (top-left 2x2):
 [[10 20]
 [50 60]]


### **Exercise 2: Accessing Matrix Elements, Rows, and Columns**

Given the following `sensor_data` matrix (representing readings from 4 sensors over 5 time steps):

```python
sensor_data = np.array([
    [2.3, 4.1, 1.9, 5.0, 3.2],  # Sensor 1
    [0.5, 1.2, 0.8, 1.5, 0.9],  # Sensor 2
    [7.1, 6.8, 7.5, 6.9, 7.0],  # Sensor 3
    [3.0, 3.5, 2.8, 3.1, 3.3]   # Sensor 4
])
```

1.  Print the entire `sensor_data` matrix.
2.  Extract and print the reading from **Sensor 3 at time step 2** (element at `[2, 1]`).
3.  Extract and print all readings from **Sensor 1** (the first row).
4.  Extract and print all readings for **time step 4** (the fourth column, index 3).
5.  Extract and print the sub-matrix containing readings from **Sensor 2 and 3** for **time steps 1 to 3** (columns 0 to 2).


In [29]:
# Your code for Exercise 2 here

sensor_data = np.array(
    [
        [2.3, 4.1, 1.9, 5.0, 3.2],  # Sensor 1
        [0.5, 1.2, 0.8, 1.5, 0.9],  # Sensor 2
        [7.1, 6.8, 7.5, 6.9, 7.0],  # Sensor 3
        [3.0, 3.5, 2.8, 3.1, 3.3],  # Sensor 4
    ]
)

print("Sensor data: \n", sensor_data)

reading_s3_t2 = sensor_data[2, 1]
print("\nReading from Sensor 3 at Time Step 2:", reading_s3_t2)

sensor_1_readings = sensor_data[0, :]
print("\nReadings from Sensor 1: ", sensor_1_readings)

timestep_4_readings = sensor_data[:, 3]
print("\nAll readings from timestap 4: ", timestep_4_readings)

sub_data = sensor_data[1:3, 0:3]
print("\nSub-matrix from Sensor 2 and 3 from time steps 1 to 3: \n", sub_data)

Sensor data: 
 [[2.3 4.1 1.9 5.  3.2]
 [0.5 1.2 0.8 1.5 0.9]
 [7.1 6.8 7.5 6.9 7. ]
 [3.  3.5 2.8 3.1 3.3]]

Reading from Sensor 3 at Time Step 2: 6.8

Readings from Sensor 1:  [2.3 4.1 1.9 5.  3.2]

All readings from timestap 4:  [5.  1.5 6.9 3.1]

Sub-matrix from Sensor 2 and 3 from time steps 1 to 3: 
 [[0.5 1.2 0.8]
 [7.1 6.8 7.5]]


In [25]:
# Solution for Exercise 2
sensor_data = np.array(
    [
        [2.3, 4.1, 1.9, 5.0, 3.2],  # Sensor 1
        [0.5, 1.2, 0.8, 1.5, 0.9],  # Sensor 2
        [7.1, 6.8, 7.5, 6.9, 7.0],  # Sensor 3
        [3.0, 3.5, 2.8, 3.1, 3.3],  # Sensor 4
    ]
)

print("Original Sensor Data Matrix:\n", sensor_data)

# 2. Reading from Sensor 3 at time step 2 (index [2, 1])
reading_s3_t2 = sensor_data[2, 1]
print("\nReading from Sensor 3 at Time Step 2:", reading_s3_t2)

# 3. All readings from Sensor 1 (first row)
sensor_1_readings = sensor_data[0, :]
print("\nReadings from Sensor 1:", sensor_1_readings)

# 4. All readings for time step 4 (fourth column, index 3)
timestep_4_readings = sensor_data[:, 3]
print("\nReadings for Time Step 4:", timestep_4_readings)

# 5. Sub-matrix for Sensor 2 and 3, time steps 1 to 3 (rows 1-2, columns 0-2)
sub_data = sensor_data[1:3, 0:3]
print("\nSub-matrix (Sensor 2-3, Time Steps 1-3):\n", sub_data)

Original Sensor Data Matrix:
 [[2.3 4.1 1.9 5.  3.2]
 [0.5 1.2 0.8 1.5 0.9]
 [7.1 6.8 7.5 6.9 7. ]
 [3.  3.5 2.8 3.1 3.3]]

Reading from Sensor 3 at Time Step 2: 6.8

Readings from Sensor 1: [2.3 4.1 1.9 5.  3.2]

Readings for Time Step 4: [5.  1.5 6.9 3.1]

Sub-matrix (Sensor 2-3, Time Steps 1-3):
 [[0.5 1.2 0.8]
 [7.1 6.8 7.5]]


## 3. Matrix Addition and Scalar Multiplication

### Concept

These operations are very similar to vector operations, applied element-wise across the matrix.

- **Matrix Addition:** To add two matrices, they **must have the same dimensions**. You add corresponding elements.

  If $A = \begin{pmatrix} a_{11} & a_{12} \\ a_{21} & a_{22} \end{pmatrix}$ and $B = \begin{pmatrix} b_{11} & b_{12} \\ b_{21} & b_{22} \end{pmatrix}$, then $A + B = \begin{pmatrix} a_{11}+b_{11} & a_{12}+b_{12} \\ a_{21}+b_{21} & a_{22}+b_{22} \end{pmatrix}$

- **Scalar Multiplication:** To multiply a matrix by a scalar, you multiply every element in the matrix by that scalar.
  If $A = \begin{pmatrix} a_{11} & a_{12} \\ a_{21} & a_{22} \end{pmatrix}$ and $c$ is a scalar, then $c A = \begin{pmatrix} c a_{11} & c a_{12} \\ c a_{21} & c a_{22} \end{pmatrix}$

### NumPy Practice

NumPy's operators `+` and `*` work directly for these element-wise matrix operations.


In [30]:
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

print("Matrix 1:\n", matrix1)
print("Matrix 2:\n", matrix2)

# Matrix Addition
matrix_sum = matrix1 + matrix2
print("\nMatrix Sum (M1 + M2):\n", matrix_sum)

# Scalar Multiplication
scalar = 2.5
scaled_matrix1 = scalar * matrix1
print("\nScaled Matrix 1 (2.5 * M1):\n", scaled_matrix1)

# Combined Operation
combined_matrix = (0.5 * matrix1) + (2 * matrix2)
print("\nCombined Matrix (0.5 * M1 + 2 * M2):\n", combined_matrix)

Matrix 1:
 [[1 2]
 [3 4]]
Matrix 2:
 [[5 6]
 [7 8]]

Matrix Sum (M1 + M2):
 [[ 6  8]
 [10 12]]

Scaled Matrix 1 (2.5 * M1):
 [[ 2.5  5. ]
 [ 7.5 10. ]]

Combined Matrix (0.5 * M1 + 2 * M2):
 [[10.5 13. ]
 [15.5 18. ]]


### **Exercise 3: Matrix Addition and Scalar Multiplication**

Suppose `daily_sales` represents sales of 3 products over 4 days, and `cost_per_product` represents the cost per unit of each product.

```python
daily_sales = np.array([
   ,  # Product A sales
   ,    # Product B sales
    # Product C sales
])

price_per_product = np.array([
    [10.0, 10.0, 10.0, 10.0], # Price A (constant over days for simplicity)
    [20.0, 20.0, 20.0, 20.0], # Price B
    [5.0, 5.0, 5.0, 5.0]     # Price C
])
```

1.  Calculate `total_revenue = daily_sales * price_per_product` (element-wise multiplication here, which is equivalent to scalar multiplication if we consider prices as scaling factors for each product's sales). _Self-correction: This is actually element-wise multiplication, not scalar. Let's make this exercise clearer by separating the concepts._

    **Revised Task 1:** Define `bonus_multiplier = 0.1`.

2.  Calculate `bonus_sales = daily_sales * bonus_multiplier`.
3.  Suppose `additional_sales` for another week are:
    `additional_sales = np.array([[3, 2, 4, 1], [1, 0, 2, 3], [5, 4, 3, 6]])`.
4.  Calculate `total_sales_over_two_weeks = daily_sales + additional_sales`.
5.  Print `daily_sales`, `bonus_sales`, `additional_sales`, and `total_sales_over_two_weeks`.


In [9]:
# Your code for Exercise 3 here
daily_sales = np.array(
    [
        [20, 14, 9, 12],
        [10, 16, 3, 14],
        [12, 14, 5, 6]
    ]
)

print("original sales:\n", daily_sales)

bonus_multiplier = 0.15
bonus_sales = daily_sales * bonus_multiplier
print("\nBonus sales (15% of daily sales):\n", bonus_sales)

total_sales_over_two_weeks = daily_sales + additional_sales

print("\nThe total sales:\n", total_sales_over_two_weeks)

original sales:
 [[20 14  9 12]
 [10 16  3 14]
 [12 14  5  6]]

Bonus sales (15% of daily sales):
 [[3.   2.1  1.35 1.8 ]
 [1.5  2.4  0.45 2.1 ]
 [1.8  2.1  0.75 0.9 ]]

The total sales:
 [[23 16 13 13]
 [11 16  5 17]
 [17 18  8 12]]


In [6]:
# Solution for Exercise 3
daily_sales = np.array(
    [
        [11, 12, 8, 15],  # Product A sales
        [5, 7, 6, 9],  # Product B sales
        [20, 18, 22, 25],  # Product C sales
    ]
)

print("Original Daily Sales:\n", daily_sales)

# 1. Scalar Multiplication: Calculate bonus sales
bonus_multiplier = 0.1
bonus_sales = daily_sales * bonus_multiplier
print("\nBonus Sales (10% of daily sales):\n", bonus_sales)

# 3. Additional sales matrix
additional_sales = np.array([[3, 2, 4, 1], [1, 0, 2, 3], [5, 4, 3, 6]])
print("\nAdditional Sales:\n", additional_sales)

# 4. Matrix Addition: Calculate total sales over two weeks
total_sales_over_two_weeks = daily_sales + additional_sales
print("\nTotal Sales (Daily + Additional):\n", total_sales_over_two_weeks)

Original Daily Sales:
 [[11 12  8 15]
 [ 5  7  6  9]
 [20 18 22 25]]

Bonus Sales (10% of daily sales):
 [[1.1 1.2 0.8 1.5]
 [0.5 0.7 0.6 0.9]
 [2.  1.8 2.2 2.5]]

Additional Sales:
 [[3 2 4 1]
 [1 0 2 3]
 [5 4 3 6]]

Total Sales (Daily + Additional):
 [[14 14 12 16]
 [ 6  7  8 12]
 [25 22 25 31]]


## 4. Matrix Transpose

### Concept

The transpose of a matrix is an operation that flips the matrix over its diagonal, exchanging the row and column indices of the matrix. The rows of the original matrix become the columns of the transposed matrix, and vice-versa.

If $A$ is an `m x n` matrix, its transpose, denoted $A^T$ (or $A'$), is an `n x m` matrix.

Example:
If $A = \begin{pmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 \end{pmatrix}$, then $A^T = \begin{pmatrix} 1 & 4 \\ 2 & 5 \\ 3 & 6 \end{pmatrix}$.

### NumPy Practice

NumPy provides a convenient `.T` attribute (or `np.transpose()`) to perform this operation.


In [12]:
original_matrix = np.array([[1, 2, 3], [4, 5, 6]])

print("Original Matrix (2x3):\n", original_matrix)
print("Shape of Original Matrix:", original_matrix.shape)

transposed_matrix = original_matrix.T  # Using the .T attribute
print("\nTransposed Matrix (3x2):\n", transposed_matrix)
print("Shape of Transposed Matrix:", transposed_matrix.shape)

print("\n---")

square_matrix = np.array([[10, 20, 30], [40, 50, 60]])
print("Square Matrix (2x2):\n", square_matrix)
print("Shape of Square Matrix:", square_matrix.shape)

transposed_square_matrix = np.transpose(square_matrix)  # Using np.transpose()
print("\nTransposed Square Matrix (2x2):\n", transposed_square_matrix)
print("Shape of Transposed Square Matrix:", transposed_square_matrix.shape)

Original Matrix (2x3):
 [[1 2 3]
 [4 5 6]]
Shape of Original Matrix: (2, 3)

Transposed Matrix (3x2):
 [[1 4]
 [2 5]
 [3 6]]
Shape of Transposed Matrix: (3, 2)

---
Square Matrix (2x2):
 [[10 20 30]
 [40 50 60]]
Shape of Square Matrix: (2, 3)

Transposed Square Matrix (2x2):
 [[10 40]
 [20 50]
 [30 60]]
Shape of Transposed Square Matrix: (3, 2)


### **Exercise 4: Matrix Transpose**

1.  Create a rectangular matrix `R` of size 5x3 (e.g., representing 5 students and 3 exam scores).
2.  Print `R` and its shape.
3.  Calculate the transpose of `R`, named `R_T`.
4.  Print `R_T` and its shape.
5.  Explain in your own words why transposing a matrix is useful in the context of handling data (e.g., if rows are samples and columns are features, what does `R_T` represent?).

    _Hint: Think about how you might want to switch the perspective of your data (e.g., from student-centric to exam-centric)._


In [15]:
# Your code for Exercise 4 here
R = np.array([
    [81, 92, 85],
    [87, 86, 91],
    [89, 87, 88],
    [87, 85, 91],
    [90, 84, 91]
])

R_T = R.T
print("\nR:\n", R)
print("\nTranspose of R:\n", R_T)
# Your explanation here:
# Why is transposing useful for data handling?
# (Type your answer here as a Python comment or in a markdown cell below)


R:
 [[81 92 85]
 [87 86 91]
 [89 87 88]
 [87 85 91]
 [90 84 91]]

Transpose of R:
 [[81 87 89 87 90]
 [92 86 87 85 84]
 [85 91 88 91 91]]


Trasnposing is useful for example if you want calculate for the indexes of the matrix.
You can calculate for Persons for a specific night or what's the probable sleep they will get tomorrow night.

In [ ]:
# Solution for Exercise 4
R = np.array(
    [
        [85, 90, 78],  # Student 1
        [92, 88, 95],  # Student 2
        [70, 75, 80],  # Student 3
        [65, 70, 68],  # Student 4
        [98, 91, 89],  # Student 5
    ]
)

print("Original Matrix R (Students x Exams):\n", R)
print("Shape of R:", R.shape)  # (5, 3)

R_T = R.T
print("\nTransposed Matrix R_T (Exams x Students):\n", R_T)
print("Shape of R_T:", R_T.shape)  # (3, 5)

print("\nExplanation of usefulness for data handling:\n")
print(
    "If the original matrix R represents `(samples x features)` (e.g., students as samples, exam scores as features),\n",
    "then its transpose R_T effectively switches this representation to `(features x samples)`.\n",
    "This is useful when you want to perform operations that treat features as primary entities instead of samples.\n",
    "For example, if you want to calculate statistics across all students for a specific exam (column in R_T),\n",
    "or if an algorithm expects features as rows rather than columns. Many linear algebra formulas\n",
    "in machine learning (like in linear regression or PCA) naturally involve matrix transposes to align dimensions correctly.",
)

## Day 3 Summary and ML Connection

Today, we laid the groundwork for working with matrices, which are ubiquitous in machine learning:

- **Matrices** are rectangular arrays of numbers. They are the standard way to represent **datasets** in machine learning, where rows typically correspond to data samples and columns to features.
- We learned to create matrices using **NumPy's 2D arrays** and to inspect their dimensions using the `.shape` attribute (e.g., `(m, n)` for `m` rows and `n` columns).
- **Accessing elements, rows, and columns** is crucial for extracting specific data points or features from a dataset.
- **Matrix Addition** and **Scalar Multiplication** are element-wise operations that are fundamental for tasks like combining data, adjusting feature scales, or applying constant transformations across all features of all samples.
- The **Matrix Transpose** operation flips the rows and columns. This is incredibly important for aligning dimensions for matrix multiplication (which we'll cover next!) and for conceptualizing data from different perspectives (e.g., `samples x features` vs. `features x samples`). It's integral to many ML algorithms' mathematical formulations (e.g., `X^T X` in linear regression).

You've now mastered the basics of matrix representation and elementary operations. Tomorrow, we'll dive into the critically important concept of **Matrix Multiplication**, which is the backbone of neural networks and many other transformations in machine learning!
