# Day 5: Special Matrices, Determinants & Trace

Welcome to Day 5, the final day of Week 1! Today, we'll explore some special types of matrices that have unique properties and specific roles in linear algebra and machine learning. We'll also introduce two important scalar values derived from square matrices: the determinant and the trace.

## Objectives for Today:

- Understand and create **Identity Matrices**.
- Understand and create **Diagonal Matrices**.
- Understand **Symmetric Matrices** and how to check for them.
- Understand **Triangular Matrices**.
- Calculate the **Determinant** of square matrices and interpret its meaning.
- Calculate the **Trace** of square matrices.
- Connect these concepts to their significance in Machine Learning.


In [2]:
# Import necessary libraries
import numpy as np

## 1. Special Matrices

### a) Identity Matrix

**Concept:** An identity matrix, denoted as $I$ (or $I_n$ for an `n x n` matrix), is a square matrix where all the elements on the main diagonal are 1s and all other elements are 0s. It acts like the number '1' in scalar multiplication (i.e., $A I = I A = A$).

Example for $I_3$ (3x3 identity matrix):

$$
I_3 = \begin{pmatrix}
1 & 0 & 0 \\
0 & 1 & 0 \\
0 & 0 & 1
\end{pmatrix}
$$

**NumPy Practice:** Use `np.identity(n)` or `np.eye(n)`.


In [ ]:
# Create a 3x3 identity matrix
identity_3x3 = np.identity(3)
print("3x3 Identity Matrix (using np.identity):\n", identity_3x3)

print("\n---")

# Create a 4x4 identity matrix using np.eye
identity_4x4 = np.eye(4)
print("4x4 Identity Matrix (using np.eye):\n", identity_4x4)

# Demonstrate A * I = A
A = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print("\nMatrix A:\n", A)
print("\nA @ I:\n", A @ identity_3x3)
print("\nAre A and A @ I equal?", np.array_equal(A, A @ identity_3x3))

3x3 Identity Matrix (using np.identity):
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

---
4x4 Identity Matrix (using np.eye):
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

Matrix A:
 [[10 20 30]
 [40 50 60]
 [70 80 90]]

A @ I:
 [[10. 20. 30.]
 [40. 50. 60.]
 [70. 80. 90.]]

Are A and A @ I equal? True


### b) Diagonal Matrix

**Concept:** A diagonal matrix is a square matrix where all the elements outside the main diagonal are zero. The diagonal elements can be any value.

Example:

$$
D = \begin{pmatrix}
2 & 0 & 0 \\
0 & -5 & 0 \\
0 & 0 & 7
\end{pmatrix}
$$

**NumPy Practice:** You can create one by passing a 1D array to `np.diag()`.


In [ ]:
# Create a diagonal matrix from a list of diagonal elements
diag_elements = np.array([2, -5, 7])
diagonal_matrix = np.diag(diag_elements)
print("Diagonal Matrix:\n", diagonal_matrix)

print("\n---")

# You can also extract the diagonal from an existing matrix
matrix_X = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
main_diagonal = np.diag(matrix_X)
print("Original Matrix X:\n", matrix_X)
print("Main diagonal of X:", main_diagonal)

Diagonal Matrix:
 [[ 2  0  0]
 [ 0 -5  0]
 [ 0  0  7]]

---
Original Matrix X:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Main diagonal of X: [1 5 9]


### c) Symmetric Matrix

**Concept:** A square matrix $A$ is symmetric if it is equal to its transpose, i.e., $A = A^T$. This means that $a_{ij} = a_{ji}$ for all $i$ and $j$.

Example:

$$
S = \begin{pmatrix}
1 & 2 & 3 \\
2 & 4 & 5 \\
3 & 5 & 6
\end{pmatrix}
$$

**NumPy Practice:** Create a matrix and compare it to its transpose using `np.array_equal()`.


In [ ]:
# Example of a symmetric matrix
symmetric_matrix = np.array([[1, 2, 3], [2, 4, 5], [3, 5, 6]])

print("Symmetric Matrix:\n", symmetric_matrix)
print("\nIts Transpose:\n", symmetric_matrix.T)
print("\nIs it symmetric?", np.array_equal(symmetric_matrix, symmetric_matrix.T))

print("---")

# Example of a non-symmetric matrix
non_symmetric_matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Non-Symmetric Matrix:\n", non_symmetric_matrix)
print("\nIts Transpose:\n", non_symmetric_matrix.T)
print(
    "\nIs it symmetric?", np.array_equal(non_symmetric_matrix, non_symmetric_matrix.T)
)

Symmetric Matrix:
 [[1 2 3]
 [2 4 5]
 [3 5 6]]

Its Transpose:
 [[1 2 3]
 [2 4 5]
 [3 5 6]]

Is it symmetric? True
---
Non-Symmetric Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Its Transpose:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]

Is it symmetric? False


### d) Triangular Matrices

**Concept:**

- **Upper Triangular Matrix:** A square matrix where all the elements _below_ the main diagonal are zero.
- **Lower Triangular Matrix:** A square matrix where all the elements _above_ the main diagonal are zero.

Example (Upper Triangular):

$$
U = \begin{pmatrix}
1 & 2 & 3 \\
0 & 4 & 5 \\
0 & 0 & 6
\end{pmatrix}
$$

**NumPy Practice:** Use `np.triu()` for upper triangular and `np.tril()` for lower triangular.


In [ ]:
square_matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print("Original Square Matrix:\n", square_matrix)

upper_triangular = np.triu(square_matrix)
print("\nUpper Triangular Matrix:\n", upper_triangular)

lower_triangular = np.tril(square_matrix)
print("\nLower Triangular Matrix:\n", lower_triangular)

# You can also specify an offset (k) for the diagonal
upper_triangular_offset = np.triu(square_matrix, k=3)  # Above the main diagonal
print("\nUpper Triangular Matrix (k=1):\n", upper_triangular_offset)

Original Square Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Upper Triangular Matrix:
 [[1 2 3]
 [0 5 6]
 [0 0 9]]

Lower Triangular Matrix:
 [[1 0 0]
 [4 5 0]
 [7 8 9]]

Upper Triangular Matrix (k=1):
 [[0 0 0]
 [0 0 0]
 [0 0 0]]


### **Exercise 1: Creating and Identifying Special Matrices**

1.  Create a 5x5 identity matrix `I5`.
2.  Create a 4x4 diagonal matrix `D` where the diagonal elements are `[10, 20, 30, 40]`.
3.  Given the matrix `M = np.array([[1, 2, 3], [2, 4, 5], [3, 5, 6]])`, determine if it is symmetric. Print the matrix, its transpose, and the boolean result.
4.  Take the matrix `P = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])`. Extract and print its lower triangular part.
5.  Print all resulting matrices/values clearly.


In [ ]:
# Your code for Exercise 1 here
I5 = np.identity(5)
print("1. 5x5 Identity Matrix:\n", I5)

D_diag_elements = np.array([10, 20, 30, 40])
D = np.diag(D_diag_elements)
print("\n 4x4 Diagonal Matrix:\n", D)

M = np.array([[1, 2, 3], [2, 4, 5], [3, 5, 6]])
print("\nMatrix M:\n", M)
print("\nThe Transpose of M:\n", M.T)
is_symmetric_M = np.array_equal(M, M.T)
print("\nIs M symmetric?\n", is_symmetric_M)

P = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
print("\nMatrix P\n:", P)
lower_P = np.tril(P)
print("\nLower Triangular P\n:", lower_P)

1. 5x5 Identity Matrix:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

 4x4 Diagonal Matrix:
 [[10  0  0  0]
 [ 0 20  0  0]
 [ 0  0 30  0]
 [ 0  0  0 40]]

Matrix M:
 [[1 2 3]
 [2 4 5]
 [3 5 6]]

The Transpose of M:
 [[1 2 3]
 [2 4 5]
 [3 5 6]]

Is M symmetric?
 True

Matrix P
: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Lower Triangular P
: [[ 1  0  0  0]
 [ 5  6  0  0]
 [ 9 10 11  0]
 [13 14 15 16]]


In [24]:
# Solution for Exercise 1
# 1. 5x5 Identity Matrix
I5 = np.identity(5)
print("1. 5x5 Identity Matrix:\n", I5)

# 2. 4x4 Diagonal Matrix
D_diag_elements = np.array([10, 20, 30, 40])
D = np.diag(D_diag_elements)
print("\n2. 4x4 Diagonal Matrix:\n", D)

# 3. Check for Symmetric Matrix
M = np.array([[1, 2, 3], [2, 4, 5], [3, 5, 6]])
print("\n3. Matrix M:\n", M)
print("Transpose of M:\n", M.T)
is_symmetric_M = np.array_equal(M, M.T)
print("Is M symmetric?", is_symmetric_M)

# 4. Lower Triangular Part
P = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
print("\n4. Original Matrix P:\n", P)
lower_P = np.tril(P)
print("Lower Triangular part of P:\n", lower_P)

1. 5x5 Identity Matrix:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

2. 4x4 Diagonal Matrix:
 [[10  0  0  0]
 [ 0 20  0  0]
 [ 0  0 30  0]
 [ 0  0  0 40]]

3. Matrix M:
 [[1 2 3]
 [2 4 5]
 [3 5 6]]
Transpose of M:
 [[1 2 3]
 [2 4 5]
 [3 5 6]]
Is M symmetric? True

4. Original Matrix P:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Lower Triangular part of P:
 [[ 1  0  0  0]
 [ 5  6  0  0]
 [ 9 10 11  0]
 [13 14 15 16]]


## 2. Determinant of a Square Matrix

### Concept

The **determinant** is a scalar value that can be computed from the elements of a square matrix. It provides important information about the matrix.

**Key Interpretations:**

- The determinant of a matrix represents the **scaling factor** of the linear transformation described by the matrix. If you transform an area/volume with the matrix, the determinant tells you how much that area/volume is scaled.
- If $\text{det}(A) = 0$, the matrix $A$ is **singular** (or non-invertible). This means the transformation collapses dimensions, e.g., mapping a 2D plane to a 1D line or a point. It implies that the matrix's columns (and rows) are linearly dependent.
- If $\text{det}(A) \neq 0$, the matrix $A$ is **invertible**, meaning a unique inverse transformation exists.

**Formulas:**

- For a 2x2 matrix $A = \begin{pmatrix} a & b \\ c & d \end{pmatrix}$, $\text{det}(A) = ad - bc$.
- For larger matrices, the calculation becomes more involved (e.g., cofactor expansion), but NumPy handles it easily.

### NumPy Practice

Use `np.linalg.det()` to calculate the determinant.


In [25]:
# 2x2 Matrix example
matrix_2x2 = np.array([[4, 1], [2, 5]])
det_2x2 = np.linalg.det(matrix_2x2)
print("Matrix 2x2:\n", matrix_2x2)
print("Determinant (4*5 - 1*2):", det_2x2)  # Expected: 20 - 2 = 18

print("\n---")

# 3x3 Matrix example
matrix_3x3 = np.array([[1, 2, 1], [3, 4, 0], [2, 1, 5]])
det_3x3 = np.linalg.det(matrix_3x3)
print("Matrix 3x3:\n", matrix_3x3)
print("Determinant:", det_3x3)

print("\n---")

# Example of a singular matrix (determinant close to zero)
# Here, row 2 is a multiple of row 0, so rows are linearly dependent
singular_matrix = np.array([[1, 2], [2, 4]])
det_singular = np.linalg.det(singular_matrix)
print("Singular Matrix:\n", singular_matrix)
print("Determinant (1*4 - 2*2):", det_singular)  # Expected: 4 - 4 = 0

Matrix 2x2:
 [[4 1]
 [2 5]]
Determinant (4*5 - 1*2): 17.999999999999996

---
Matrix 3x3:
 [[1 2 1]
 [3 4 0]
 [2 1 5]]
Determinant: -15.000000000000007

---
Singular Matrix:
 [[1 2]
 [2 4]]
Determinant (1*4 - 2*2): 0.0


### **Exercise 2: Calculating Determinants**

1.  Calculate the determinant of `M1 = np.array([[6, 3], [2, 1]])`.
2.  Calculate the determinant of `M2 = np.array([[1, 2, 3], [0, 1, 4], [5, 6, 0]])`.
3.  Create a matrix `M3` where the determinant is very close to zero (indicating linear dependence of rows/columns). You can achieve this by making one row a linear combination of others. For example, in a 3x3 matrix, `row3 = row1 + row2`.
4.  Print all matrices and their determinants.
5.  For `M1`, interpret what its determinant means regarding the invertibility of the matrix and the linear independence of its columns/rows.
    _Hint: If det is 0, it's singular. If not 0, it's invertible._


In [3]:
# Your code for Exercise 2 here
M1 = np.array([[6, 3], [2, 1]])
det_M1 = np.linalg.det(M1)
print("Matrix M1:\n", M1)
print("\nDeterminant of M1:\n", det_M1)
# Your interpretation for M1's determinant here:
if np.isclose(det_M1, 0):
    print("The determinant is 0, so the transformation collapses into a singular dimension.")
else:
    print("The determinant ≠ 0 , so the transfomation is invertable.")

M2 = np.array([[1, 2, 3], [0, 1, 4], [5, 6, 0]])
det_M2 = np.linalg.det(M2)
print("Matrix M2:\n", M2)
print("\nDeterminant of M2:\n", det_M2)

M3 = np.array([[1, 3, 6], [4, 10, 2], [5, 13, 8]])
det_M3 = np.linalg.det(M3)
print("Matrix M3:\n", M3)
print("\nDeterminant of M3:\n", det_M3)


Matrix M1:
 [[6 3]
 [2 1]]

Determinant of M1:
 0.0
The determinant is 0, so the transformation collapses into a singular dimension.
Matrix M2:
 [[1 2 3]
 [0 1 4]
 [5 6 0]]

Determinant of M2:
 0.9999999999999964
Matrix M3:
 [[ 1  3  6]
 [ 4 10  2]
 [ 5 13  8]]

Determinant of M3:
 1.0658141036401509e-14


In [4]:
# Solution for Exercise 2
# 1. Determinant of M1
M1 = np.array([[6, 3], [2, 1]])
det_M1 = np.linalg.det(M1)
print("Matrix M1:\n", M1)
print("Determinant of M1:", det_M1)

# Interpretation for M1:
if np.isclose(det_M1, 0):
    print(
        "Interpretation for M1: The determinant is 0. This means M1 is a singular (non-invertible) matrix."
    )
    print(
        "Its columns (or rows) are linearly dependent, meaning one is a scalar multiple of the other.\n",
        "Geometrically, it collapses the space, e.g., mapping a 2D area to a 1D line.",
    )
else:
    print(
        "Interpretation for M1: The determinant is non-zero. This means M1 is an invertible matrix."
    )
    print(
        "Its columns (or rows) are linearly independent. Geometrically, it scales the space without collapsing it."
    )

# 2. Determinant of M2
M2 = np.array([[1, 2, 3], [0, 1, 4], [5, 6, 0]])
det_M2 = np.linalg.det(M2)
print("\nMatrix M2:\n", M2)
print("Determinant of M2:", det_M2)

# 3. Create a matrix with determinant close to zero
M3 = np.array([[1, 2, 3], [4, 5, 6], [5, 7, 9]])  # row3 = row1 + row2
det_M3 = np.linalg.det(M3)
print("\nMatrix M3 (designed to be singular):\n", M3)
print("Determinant of M3:", det_M3)  # Should be very close to 0

Matrix M1:
 [[6 3]
 [2 1]]
Determinant of M1: 0.0
Interpretation for M1: The determinant is 0. This means M1 is a singular (non-invertible) matrix.
Its columns (or rows) are linearly dependent, meaning one is a scalar multiple of the other.
 Geometrically, it collapses the space, e.g., mapping a 2D area to a 1D line.

Matrix M2:
 [[1 2 3]
 [0 1 4]
 [5 6 0]]
Determinant of M2: 0.9999999999999964

Matrix M3 (designed to be singular):
 [[1 2 3]
 [4 5 6]
 [5 7 9]]
Determinant of M3: 2.664535259100367e-15


## 3. Trace of a Square Matrix

### Concept

The **trace** of a square matrix is the sum of the elements on its main diagonal. It's a simple scalar value, but it has surprising applications in various mathematical and engineering fields, including matrix calculus and quantum mechanics.

For $A = \begin{pmatrix} a_{11} & a_{12} & a_{13} \\ a_{21} & a_{22} & a_{23} \\ a_{31} & a_{32} & a_{33} \end{pmatrix}$, $\text{trace}(A) = a_{11} + a_{22} + a_{33}$.

### NumPy Practice

Use `np.trace()` to calculate the trace.


In [5]:
matrix_trace = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

trace_value = np.trace(matrix_trace)
print("Matrix:\n", matrix_trace)
print("Trace (1 + 5 + 9):", trace_value)  # Expected: 15

print("\n---")

another_matrix = np.array([[10, 0], [-3, 7]])
another_trace = np.trace(another_matrix)
print("Another Matrix:\n", another_matrix)
print("Trace (10 + 7):", another_trace)  # Expected: 17

Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Trace (1 + 5 + 9): 15

---
Another Matrix:
 [[10  0]
 [-3  7]]
Trace (10 + 7): 17


### **Exercise 3: Calculating the Trace**

1.  Calculate the trace of `S1 = np.array([[10, -2], [5, 12]])`.
2.  Calculate the trace of `S2 = np.array([[1, 1, 1], [2, 2, 2], [3, 3, 3]])`.
3.  Calculate the trace of a 4x4 identity matrix.
4.  Print all matrices and their traces.


In [8]:
# Your code for Exercise 3 here
S1 = np.array([[10, -2], [5, 12]])
trace_S1 = np.trace(S1)
print("Matrix S1:\n", S1)
print("\nTrace of S1:\n", trace_S1)

S2 = np.array([[1, 1, 1], [2, 2, 2], [3, 3, 3]])
trace_S2 = np.trace(S2)
print("\nMatrix S2:\n", S2)
print("\nTrace of S2:\n", trace_S2)

I4 = np.identity(4)
trace_I4 = np.trace(I4)
print("\nMatrix I4:\n", I4)
print("\nTrace of I4:\n", trace_I4)

Matrix S1:
 [[10 -2]
 [ 5 12]]

Trace of S1:
 22

Matrix S2:
 [[1 1 1]
 [2 2 2]
 [3 3 3]]

Trace of S2:
 6

Matrix I4:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

Trace of I4:
 4.0


In [9]:
# Solution for Exercise 3
# 1. Trace of S1
S1 = np.array([[10, -2], [5, 12]])
trace_S1 = np.trace(S1)
print("Matrix S1:\n", S1)
print("Trace of S1:", trace_S1)  # Expected: 10 + 12 = 22

# 2. Trace of S2
S2 = np.array([[1, 1, 1], [2, 2, 2], [3, 3, 3]])
trace_S2 = np.trace(S2)
print("\nMatrix S2:\n", S2)
print("Trace of S2:", trace_S2)  # Expected: 1 + 2 + 3 = 6

# 3. Trace of a 4x4 identity matrix
I4 = np.identity(4)
trace_I4 = np.trace(I4)
print("\n4x4 Identity Matrix:\n", I4)
print("Trace of I4:", trace_I4)  # Expected: 1 + 1 + 1 + 1 = 4

Matrix S1:
 [[10 -2]
 [ 5 12]]
Trace of S1: 22

Matrix S2:
 [[1 1 1]
 [2 2 2]
 [3 3 3]]
Trace of S2: 6

4x4 Identity Matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Trace of I4: 4.0


## Day 5 Summary and ML Connection

We've covered several important concepts today, completing our first week of linear algebra fundamentals:

- **Special Matrices:**

  - **Identity Matrix ($I$):** Acts like '1' in matrix multiplication, representing no change or transformation. Important for matrix inverses and defining bases.
  - **Diagonal Matrix:** Non-zero elements only on the main diagonal. Simplifies calculations and is seen in various decompositions (like SVD).
  - **Symmetric Matrix:** Equal to its transpose. Crucial in covariance matrices (for PCA), spectral graph theory, and quadratic forms in optimization.
  - **Triangular Matrices:** All elements above or below the main diagonal are zero. Useful in solving systems of linear equations (Gaussian elimination) and matrix factorizations (LU decomposition).

- **Determinant:** A scalar value for square matrices indicating the scaling factor of the transformation and the invertibility of the matrix.

  - **det(A) = 0:** Matrix is singular, columns/rows are linearly dependent, implies a loss of dimension/information in the transformation.
  - **det(A) ≠ 0:** Matrix is invertible, columns/rows are linearly independent, implies a reversible transformation.
  - Crucial for understanding systems of equations, eigenvalue calculations, and matrix invertibility (which we'll see next week!).

- **Trace:** The sum of the diagonal elements of a square matrix.
  - While seemingly simple, it has connections to eigenvalues (sum of eigenvalues equals the trace) and is used in various formulas in machine learning, such as in the calculation of variance or certain regularization terms.

Congratulations on completing Week 1! You've built a strong foundation in vector and matrix basics, operations, and special types. Next week, we'll dive into more advanced topics like inverse matrices, eigenvalues, eigenvectors, and the powerful Singular Value Decomposition, all of which are directly applicable to complex machine learning problems.
