# Day 8: Singular Value Decomposition (SVD) - Introduction

Welcome to Day 8! Today, we'll learn about one of the most powerful and versatile matrix decomposition techniques in linear algebra: **Singular Value Decomposition (SVD)**. SVD is more general than eigendecomposition because it works on *any* matrix, not just square ones. It is a cornerstone of many machine learning applications, from dimensionality reduction to recommender systems.

## Objectives for Today:
- Understand how SVD decomposes a matrix into three simpler matrices (U, Σ, Vᵀ).
- See the relationship between SVD and eigenvalues for symmetric matrices.
- Learn how to perform SVD on a matrix using NumPy.
- Reconstruct a matrix from its SVD components.
- Perform low-rank approximation by truncating singular values.
- Connect SVD to its applications in ML, like image compression and dimensionality reduction.

In [1]:
# Import necessary libraries
import numpy as np

## 1. What is Singular Value Decomposition?

SVD states that any matrix `A` (of shape `m x n`) can be factored into three separate matrices:

### **`A = UΣVᵀ`**

Where:
-   **`A`** is the original `m x n` matrix.
-   **`U`** is an `m x m` orthogonal matrix. Its columns are the **left-singular vectors**.
-   **`Σ`** (Sigma) is an `m x n` diagonal matrix. Its diagonal entries are the **singular values** of `A`. These values are always non-negative and are ordered from largest to smallest.
-   **`Vᵀ`** is the transpose of an `n x n` orthogonal matrix `V`. The columns of `V` (and thus rows of `Vᵀ`) are the **right-singular vectors**.

**Key Idea:** SVD breaks down a complex transformation (matrix `A`) into a series of simpler transformations: a rotation (`Vᵀ`), a scaling (`Σ`), and another rotation (`U`). The singular values in `Σ` tell us the importance of each dimension in this transformation.

## 2. SVD with NumPy

NumPy's `np.linalg.svd()` function is the tool we use to perform SVD.

It returns a tuple of three arrays: `U`, `s`, and `Vh`.
-   `U` is the matrix of left-singular vectors.
-   `s` is a **1D array** containing the singular values (the diagonal of `Σ`). It is *not* the full `Σ` matrix.
-   `Vh` is the transposed matrix of right-singular vectors (`Vᵀ`).

In [ ]:
# Define a non-square matrix
A = np.array([[1, 2],
              [3, 4],
              [5, 6]])

print("Matrix A:\n", A)

# Perform SVD
U, s, Vh = np.linalg.svd(A)

print("\n---")
print("U:\n", U)
print("Shape of U:", U.shape)

print("\nSingular values (s):\n", s)
print("Shape of s:", s.shape)

print("\nV transpose (Vh):\n", Vh)
print("Shape of Vh:", Vh.shape)

Matrix A:
 [[1 2]
 [3 4]
 [5 6]]

---
U:
 [[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]
Shape of U: (3, 3)

Singular values (s):
 [9.52551809 0.51430058]
Shape of s: (2,)

V transpose (Vh):
 [[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]
Shape of Vh: (2, 2)


### **Exercise 1: Reconstructing the Original Matrix**

To reconstruct `A`, we need to convert the 1D array `s` into the `m x n` diagonal matrix `Σ`. Then we can multiply `U @ Σ @ Vh`.

1.  Initialize a zero matrix `Sigma` with the same shape as the original matrix `A` (`3 x 2`).
2.  Fill the diagonal of `Sigma` with the singular values from `s`.
3.  Reconstruct `A` by multiplying the three matrices.
4.  Use `np.allclose()` to check if the reconstructed matrix is close to the original `A`.

In [9]:
# Your code for Exercise 1 here
Sigma = np.zeros(A.shape)
Sigma[:A.shape[1], :A.shape[1]] = np.diag(s)

print("Sigma (Σ) matrix:\n", Sigma)

A_reconstructed = U @ Sigma @Vh
print("\nReconstructed Matrix:\n", A_reconstructed)

print("\nIs the original matrix similar to the reconstructed?\n", np.allclose(A, A_reconstructed))

Sigma (Σ) matrix:
 [[9.52551809 0.        ]
 [0.         0.51430058]
 [0.         0.        ]]

Reconstructed Matrix:
 [[1. 2.]
 [3. 4.]
 [5. 6.]]

Is the original matrix similar to the reconstructed?
 True


In [ ]:
# Solution

# 1. Create a zero matrix with the correct shape
Sigma = np.zeros(A.shape) # (3, 2)

# 2. Fill the diagonal with singular values
Sigma[:A.shape[1], :A.shape[1]] = np.diag(s) # Fill 2x2 part

print("Sigma (Σ) matrix:\n", Sigma)

# 3. Reconstruct A
A_reconstructed = U @ Sigma @ Vh

print("\nReconstructed Matrix:\n", A_reconstructed)

# 4. Check for closeness
print("\nIs the reconstructed matrix close to the original?", np.allclose(A, A_reconstructed))

Sigma (Σ) matrix:
 [[9.52551809 0.        ]
 [0.         0.51430058]
 [0.         0.        ]]

Reconstructed Matrix:
 [[1. 2.]
 [3. 4.]
 [5. 6.]]

Is the reconstructed matrix close to the original? True


## 3. Low-Rank Approximation

The magic of SVD is that the largest singular values correspond to the most significant "parts" of the matrix. We can create a **low-rank approximation** of the original matrix by keeping only the top `k` singular values.

This is incredibly useful for compressing data, as we only need to store the first `k` columns of `U`, the first `k` singular values, and the first `k` rows of `Vh`.

In [10]:
# Perform a rank-1 approximation (k=1)
k = 1

U_k = U[:, :k]         # First k columns of U
s_k = s[:k]           # First k singular values
Vh_k = Vh[:k, :]      # First k rows of Vh

# Reconstruct the rank-1 matrix
A_approx_k1 = U_k @ np.diag(s_k) @ Vh_k

print("Original matrix A:\n", A)
print("\nRank-1 Approximation of A:\n", A_approx_k1)

Original matrix A:
 [[1 2]
 [3 4]
 [5 6]]

Rank-1 Approximation of A:
 [[1.35662819 1.71846235]
 [3.09719707 3.92326845]
 [4.83776596 6.12807454]]


### **Exercise 2: Perform a Low-Rank Approximation**

1.  Define a new matrix `B`:
    ```
    B = np.array([,
                  [-1, 3, 1]])
    ```
2.  Perform SVD on matrix `B`.
3.  Create and print a **rank-1 approximation** of `B`.
4.  Notice how the rank-1 approximation captures the general structure but loses some detail.

In [15]:
# Your code for Exercise 2 here
B = np.array([[9, 2, 5], [-1, 3, 1]])

U_b, s_b, Vh_b = np.linalg.svd(B)

k = 1

B_approx_k1 = U_b[:, :k] @ np.diag(s_b[:k]) @ Vh_b[:k, :]

print("Original Matrix B:\n", B)
print("\nRank-1 Approximation of B:\n", B_approx_k1)

Original Matrix B:
 [[ 9  2  5]
 [-1  3  1]]

Rank-1 Approximation of B:
 [[8.97614585 2.05974141 5.01814744]
 [0.18126233 0.04159397 0.10133538]]


In [11]:
# Solution

B = np.array([[3, 1, 1], [-1, 3, 1]])

# Perform SVD
U_b, s_b, Vh_b = np.linalg.svd(B)

# Create rank-1 approximation
k = 1
B_approx_k1 = U_b[:, :k] @ np.diag(s_b[:k]) @ Vh_b[:k, :]

print("Original Matrix B:\n", B)
print("\nRank-1 Approximation of B:\n", B_approx_k1)

Original Matrix B:
 [[ 3  1  1]
 [-1  3  1]]

Rank-1 Approximation of B:
 [[1. 2. 1.]
 [1. 2. 1.]]


## 4. ML Connection: Compression, Recommenders, and more

SVD is one of the most useful algorithms in machine learning.

-   **Dimensionality Reduction & PCA:** SVD is the mathematical engine behind Principal Component Analysis. It finds the principal components by performing SVD on the centered data matrix.

-   **Image Compression:** An image can be represented as a matrix of pixel values. A low-rank approximation of this matrix using SVD can capture the essential features of the image while using significantly less data to store.

-   **Recommender Systems:** In a user-item matrix (where rows are users and columns are items they've rated), SVD can help find latent (hidden) factors. The low-rank approximation can predict missing ratings, forming the basis of matrix factorization techniques for recommendations.

-   **Natural Language Processing (NLP):** SVD is used in Latent Semantic Analysis (LSA) to analyze relationships between documents and terms, helping to uncover underlying topics in a large corpus of text.

## Day 8 Summary and Key Takeaways

Excellent work! SVD is a fundamental technique that unlocks many advanced applications.

Here's what we covered:
-   SVD decomposes **any** matrix `A` into `UΣVᵀ`.
-   `U` and `V` are orthogonal matrices (rotations), and `Σ` is a diagonal matrix of singular values (scaling).
-   `np.linalg.svd()` is the function to use, but remember it returns the singular values as a 1D array `s`.
-   **Low-rank approximation** is the key application, where we use the top `k` singular values to create a compressed version of the original matrix.
-   This simple idea is the basis for powerful techniques in PCA, image compression, and recommender systems.

Tomorrow, we'll dive into the more abstract but crucial concepts of vector spaces, subspaces, and the rank of a matrix.